//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("Application.Demo.ClickOnce")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("Dapplo")]
[assembly: AssemblyProduct("Application.Demo.ClickOnce")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0-beta")]
[assembly: AssemblyCopyright("Copyright © Dapplo 2018")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

